import { FeedItem, FamilyMember } from '../types';

export const mockFeedItems: FeedItem[] = [
  {
    id: '1',
    type: 'memory',
    authorId: 'user1',
    authorName: 'Grandma Rose',
    authorPhotoURL: 'https://i.pravatar.cc/150?img=1',
    content: {
      text: "Remember when we used to make apple pie together every fall? The kitchen would smell so wonderful. I miss those afternoons with all of you.",
      mediaURLs: [],
    },
    hearts: ['user2', 'user3'],
    createdAt: new Date('2024-01-15T10:30:00'),
    updatedAt: new Date('2024-01-15T10:30:00'),
  },
  {
    id: '2',
    type: 'photo',
    authorId: 'user2',
    authorName: 'Dad',
    authorPhotoURL: 'https://i.pravatar.cc/150?img=3',
    content: {
      text: 'Found this old photo from our 1995 camping trip!',
      mediaURLs: ['https://picsum.photos/400/300'],
    },
    hearts: ['user1'],
    createdAt: new Date('2024-01-14T15:00:00'),
    updatedAt: new Date('2024-01-14T15:00:00'),
  },
  {
    id: '3',
    type: 'prompt_response',
    authorId: 'user3',
    authorName: 'Mom',
    authorPhotoURL: 'https://i.pravatar.cc/150?img=5',
    content: {
      text: "The best advice my parents gave me was to always treat others the way you want to be treated. Simple but powerful.",
      promptId: 'prompt1',
      promptText: 'What was the best advice your parents gave you?',
    },
    hearts: ['user1', 'user2', 'user4'],
    createdAt: new Date('2024-01-13T09:15:00'),
    updatedAt: new Date('2024-01-13T09:15:00'),
  },
  {
    id: '4',
    type: 'milestone',
    authorId: 'user4',
    authorName: 'Sister Sarah',
    authorPhotoURL: 'https://i.pravatar.cc/150?img=9',
    content: {
      text: 'Little Emma took her first steps today! So proud of my baby girl.',
      mediaURLs: ['https://picsum.photos/400/500'],
    },
    hearts: ['user1', 'user2', 'user3'],
    createdAt: new Date('2024-01-12T18:45:00'),
    updatedAt: new Date('2024-01-12T18:45:00'),
  },
];

export const mockFamilyMembers: FamilyMember[] = [
  // Grandparents
  {
    id: 'member1',
    firstName: 'Rose',
    lastName: 'Herman',
    nickname: 'Grandma Rose',
    photoURL: 'https://i.pravatar.cc/150?img=1',
    birthDate: new Date('1945-03-15'),
    bio: 'Retired teacher. Loves gardening and baking.',
    relationships: [
      { memberId: 'grandpa1', type: 'spouse' },
      { memberId: 'member2', type: 'child' },
      { memberId: 'member3', type: 'child' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'grandpa1',
    firstName: 'Walter',
    lastName: 'Herman',
    nickname: 'Grandpa Walt',
    photoURL: 'https://i.pravatar.cc/150?img=12',
    birthDate: new Date('1942-08-20'),
    bio: 'Retired carpenter. Loves fishing.',
    relationships: [
      { memberId: 'member1', type: 'spouse' },
      { memberId: 'member2', type: 'child' },
      { memberId: 'member3', type: 'child' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // Parents generation
  {
    id: 'member2',
    firstName: 'David',
    lastName: 'Herman',
    nickname: 'Dad',
    photoURL: 'https://i.pravatar.cc/150?img=3',
    birthDate: new Date('1970-07-22'),
    bio: 'Engineer. Weekend golfer.',
    relationships: [
      { memberId: 'member1', type: 'parent' },
      { memberId: 'grandpa1', type: 'parent' },
      { memberId: 'member4', type: 'spouse' },
      { memberId: 'member5', type: 'child' },
      { memberId: 'member6', type: 'child' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member4',
    firstName: 'Linda',
    lastName: 'Herman',
    nickname: 'Mom',
    photoURL: 'https://i.pravatar.cc/150?img=5',
    birthDate: new Date('1972-04-12'),
    bio: 'Nurse. Loves reading and cooking.',
    relationships: [
      { memberId: 'member2', type: 'spouse' },
      { memberId: 'member5', type: 'child' },
      { memberId: 'member6', type: 'child' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member3',
    firstName: 'Sarah',
    lastName: 'Thompson',
    nickname: 'Aunt Sarah',
    photoURL: 'https://i.pravatar.cc/150?img=9',
    birthDate: new Date('1975-11-08'),
    bio: 'Artist and mother of two.',
    relationships: [
      { memberId: 'member1', type: 'parent' },
      { memberId: 'grandpa1', type: 'parent' },
      { memberId: 'member2', type: 'sibling' },
      { memberId: 'member7', type: 'child' },
      { memberId: 'member8', type: 'child' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // Children generation
  {
    id: 'member5',
    firstName: 'Eli',
    lastName: 'Herman',
    photoURL: 'https://i.pravatar.cc/150?img=11',
    birthDate: new Date('1998-02-14'),
    bio: 'Software developer.',
    relationships: [
      { memberId: 'member2', type: 'parent' },
      { memberId: 'member4', type: 'parent' },
      { memberId: 'member6', type: 'sibling' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member6',
    firstName: 'Emma',
    lastName: 'Herman',
    photoURL: 'https://i.pravatar.cc/150?img=25',
    birthDate: new Date('2001-09-03'),
    bio: 'College student studying biology.',
    relationships: [
      { memberId: 'member2', type: 'parent' },
      { memberId: 'member4', type: 'parent' },
      { memberId: 'member5', type: 'sibling' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member7',
    firstName: 'Jake',
    lastName: 'Thompson',
    nickname: 'Cousin Jake',
    photoURL: 'https://i.pravatar.cc/150?img=33',
    birthDate: new Date('2000-06-18'),
    bio: 'Musician.',
    relationships: [
      { memberId: 'member3', type: 'parent' },
      { memberId: 'member8', type: 'sibling' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member8',
    firstName: 'Lily',
    lastName: 'Thompson',
    nickname: 'Cousin Lily',
    photoURL: 'https://i.pravatar.cc/150?img=44',
    birthDate: new Date('2005-12-25'),
    bio: 'High school student.',
    relationships: [
      { memberId: 'member3', type: 'parent' },
      { memberId: 'member7', type: 'sibling' },
    ],
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockPrompts = [
  {
    id: 'prompt1',
    text: 'What was the best advice your parents gave you?',
    category: 'life_lessons' as const,
    isActive: true,
  },
  {
    id: 'prompt2',
    text: "What's your favorite family tradition?",
    category: 'family_traditions' as const,
    isActive: true,
  },
  {
    id: 'prompt3',
    text: 'What was your favorite childhood memory?',
    category: 'childhood' as const,
    isActive: true,
  },
];
