import { FeedItem, FamilyMember } from '../types';

// Herman Family Mock Data
// 9 members across 3 generations
// Relationships stored: parent/child, spouse (siblings derived at runtime from shared parents)

export const mockFamilyMembers: FamilyMember[] = [
  // Generation 1 (Grandparents)
  {
    id: 'peggy',
    firstName: 'Peggy',
    lastName: 'Deleenheer',
    nickname: 'Grandma',
    gender: 'female',
    photoURL: 'https://i.pravatar.cc/150?u=peggy',
    birthDate: new Date('1948-05-12'),
    bio: 'Loves gardening, baking, and spending time with grandchildren. Always has a warm cookie ready.',
    relationships: [
      { memberId: 'ron', type: 'spouse' },
      { memberId: 'shelby', type: 'child' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'ron',
    firstName: 'Ron',
    lastName: 'Deleenheer',
    nickname: 'Grandpa',
    gender: 'male',
    photoURL: 'https://i.pravatar.cc/150?u=ron',
    birthDate: new Date('1946-08-23'),
    bio: 'Retired engineer who still loves tinkering in the garage. Teaches the grandkids about cars.',
    relationships: [
      { memberId: 'peggy', type: 'spouse' },
      { memberId: 'shelby', type: 'child' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Generation 2 (Parents)
  {
    id: 'shelby',
    firstName: 'Shelby',
    lastName: 'Herman',
    nickname: 'Mom',
    gender: 'female',
    photoURL: 'https://i.pravatar.cc/150?u=shelby',
    birthDate: new Date('1972-03-15'),
    bio: 'Heart of the family. Loves hosting dinners and keeping everyone connected.',
    relationships: [
      { memberId: 'peggy', type: 'parent' },
      { memberId: 'ron', type: 'parent' },
      { memberId: 'timothy', type: 'spouse' },
      { memberId: 'ella', type: 'child' },
      { memberId: 'eli', type: 'child' },
      { memberId: 'bennett', type: 'child' },
      { memberId: 'ember', type: 'child' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'timothy',
    firstName: 'Timothy',
    lastName: 'Herman',
    nickname: 'Dad',
    gender: 'male',
    photoURL: 'https://i.pravatar.cc/150?u=timothy',
    birthDate: new Date('1970-11-08'),
    bio: 'Works hard, loves harder. Enjoys camping trips and teaching life lessons.',
    relationships: [
      { memberId: 'shelby', type: 'spouse' },
      { memberId: 'ella', type: 'child' },
      { memberId: 'eli', type: 'child' },
      { memberId: 'bennett', type: 'child' },
      { memberId: 'ember', type: 'child' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Generation 3 (Siblings + In-law)
  {
    id: 'ella',
    firstName: 'Ella',
    lastName: 'Fu',
    gender: 'female',
    photoURL: 'https://i.pravatar.cc/150?u=ella',
    birthDate: new Date('1996-07-22'),
    bio: 'Oldest sibling. Creative soul who loves art and photography. Recently married to Preston.',
    relationships: [
      { memberId: 'shelby', type: 'parent' },
      { memberId: 'timothy', type: 'parent' },
      { memberId: 'preston', type: 'spouse' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'preston',
    firstName: 'Preston',
    lastName: 'Fu',
    gender: 'male',
    photoURL: 'https://i.pravatar.cc/150?u=preston',
    birthDate: new Date('1995-02-14'),
    bio: "Ella's husband. Software engineer and board game enthusiast. Welcomed into the family with open arms.",
    relationships: [
      { memberId: 'ella', type: 'spouse' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'eli',
    firstName: 'Eli',
    lastName: 'Herman',
    gender: 'male',
    photoURL: 'https://i.pravatar.cc/150?u=eli',
    birthDate: new Date('1998-09-03'),
    bio: 'The family tech guy. Building apps to bring people closer together.',
    relationships: [
      { memberId: 'shelby', type: 'parent' },
      { memberId: 'timothy', type: 'parent' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'bennett',
    firstName: 'Bennett',
    lastName: 'Herman',
    gender: 'male',
    photoURL: 'https://i.pravatar.cc/150?u=bennett',
    birthDate: new Date('2001-04-17'),
    bio: 'Younger brother. Sports fan and aspiring musician. Always up for an adventure.',
    relationships: [
      { memberId: 'shelby', type: 'parent' },
      { memberId: 'timothy', type: 'parent' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'ember',
    firstName: 'Ember',
    lastName: 'Herman',
    gender: 'female',
    photoURL: 'https://i.pravatar.cc/150?u=ember',
    birthDate: new Date('2004-12-25'),
    bio: 'Baby of the family. Loves animals and dreams of becoming a veterinarian.',
    relationships: [
      { memberId: 'shelby', type: 'parent' },
      { memberId: 'timothy', type: 'parent' },
    ],
    createdBy: 'eli',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Feed items using Herman family member IDs
export const mockFeedItems: FeedItem[] = [
  {
    id: '1',
    type: 'memory',
    authorId: 'peggy',
    authorName: 'Peggy Deleenheer',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=peggy',
    content: {
      text: "Remember when we used to make apple pie together every fall? The kitchen would smell so wonderful. I miss those afternoons with all of you gathered around.",
      mediaURLs: [],
    },
    hearts: ['eli', 'shelby', 'ella'],
    comments: [
      {
        id: 'comment-1-1',
        authorId: 'shelby',
        authorName: 'Shelby Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=shelby',
        text: 'I still remember that cinnamon smell! We should make pies together this fall.',
        createdAt: new Date('2026-01-28T11:00:00'),
      },
      {
        id: 'comment-1-2',
        authorId: 'eli',
        authorName: 'Eli Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=eli',
        text: 'Best pies ever, Grandma!',
        createdAt: new Date('2026-01-28T12:30:00'),
      },
    ],
    createdAt: new Date('2026-01-28T10:30:00'),
    updatedAt: new Date('2026-01-28T10:30:00'),
  },
  {
    id: '2',
    type: 'photo',
    authorId: 'timothy',
    authorName: 'Timothy Herman',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=timothy',
    content: {
      text: 'Found this old photo from our 2015 camping trip! Look how little everyone was.',
      mediaURLs: ['https://picsum.photos/400/300?random=1'],
    },
    hearts: ['shelby', 'ella', 'eli', 'bennett', 'ember'],
    comments: [
      {
        id: 'comment-2-1',
        authorId: 'bennett',
        authorName: 'Bennett Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=bennett',
        text: 'Haha I was so small! That was such a fun trip.',
        createdAt: new Date('2026-01-27T16:00:00'),
      },
      {
        id: 'comment-2-2',
        authorId: 'ember',
        authorName: 'Ember Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=ember',
        text: 'I remember the s\'mores! Can we go camping again soon?',
        createdAt: new Date('2026-01-27T17:15:00'),
      },
      {
        id: 'comment-2-3',
        authorId: 'peggy',
        authorName: 'Peggy Deleenheer',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=peggy',
        text: 'Such precious memories. You all grow up so fast.',
        createdAt: new Date('2026-01-27T18:00:00'),
      },
    ],
    createdAt: new Date('2026-01-27T15:00:00'),
    updatedAt: new Date('2026-01-27T15:00:00'),
  },
  {
    id: '3',
    type: 'prompt_response',
    authorId: 'shelby',
    authorName: 'Shelby Herman',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=shelby',
    content: {
      text: "The best advice my parents gave me was to always treat others the way you want to be treated. Simple but powerful. I've tried to pass this on to all of you.",
      promptId: 'prompt1',
      promptText: 'What was the best advice your parents gave you?',
    },
    hearts: ['peggy', 'ron', 'eli', 'bennett', 'ember'],
    comments: [
      {
        id: 'comment-3-1',
        authorId: 'ron',
        authorName: 'Ron Deleenheer',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=ron',
        text: 'Your mother and I are so proud of the person you\'ve become, Shelby.',
        createdAt: new Date('2026-01-26T10:00:00'),
      },
      {
        id: 'comment-3-2',
        authorId: 'eli',
        authorName: 'Eli Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=eli',
        text: 'This is definitely something I think about often. Thanks for teaching us, Mom.',
        createdAt: new Date('2026-01-26T11:30:00'),
      },
    ],
    createdAt: new Date('2026-01-26T09:15:00'),
    updatedAt: new Date('2026-01-26T09:15:00'),
  },
  {
    id: '4',
    type: 'milestone',
    authorId: 'ella',
    authorName: 'Ella Fu',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=ella',
    content: {
      text: "Preston and I just celebrated our first wedding anniversary! Thank you all for your love and support.",
      mediaURLs: ['https://picsum.photos/400/500?random=2'],
    },
    hearts: ['peggy', 'ron', 'shelby', 'timothy', 'eli', 'bennett', 'ember'],
    comments: [
      {
        id: 'comment-4-1',
        authorId: 'shelby',
        authorName: 'Shelby Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=shelby',
        text: 'Happy anniversary sweetie! So happy for you both!',
        createdAt: new Date('2026-01-25T19:00:00'),
      },
      {
        id: 'comment-4-2',
        authorId: 'timothy',
        authorName: 'Timothy Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=timothy',
        text: 'Congratulations! Here\'s to many more years together.',
        createdAt: new Date('2026-01-25T19:30:00'),
      },
      {
        id: 'comment-4-3',
        authorId: 'peggy',
        authorName: 'Peggy Deleenheer',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=peggy',
        text: 'A whole year already! Time flies when you\'re happy. Love you both.',
        createdAt: new Date('2026-01-25T20:00:00'),
      },
    ],
    createdAt: new Date('2026-01-25T18:45:00'),
    updatedAt: new Date('2026-01-25T18:45:00'),
  },
  {
    id: '5',
    type: 'photo',
    authorId: 'bennett',
    authorName: 'Bennett Herman',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=bennett',
    content: {
      text: 'Band practice going well! First gig next month.',
      mediaURLs: ['https://picsum.photos/400/400?random=3'],
    },
    hearts: ['shelby', 'timothy', 'eli'],
    comments: [
      {
        id: 'comment-5-1',
        authorId: 'timothy',
        authorName: 'Timothy Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=timothy',
        text: 'Can\'t wait to see you perform! So proud of you.',
        createdAt: new Date('2026-01-24T21:00:00'),
      },
      {
        id: 'comment-5-2',
        authorId: 'ember',
        authorName: 'Ember Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=ember',
        text: 'You guys sound so good! I want front row seats!',
        createdAt: new Date('2026-01-24T21:30:00'),
      },
    ],
    createdAt: new Date('2026-01-24T20:00:00'),
    updatedAt: new Date('2026-01-24T20:00:00'),
  },
  {
    id: '6',
    type: 'memory',
    authorId: 'ron',
    authorName: 'Ron Deleenheer',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=ron',
    content: {
      text: "Taught Bennett how to change a tire last weekend. Passing down what my dad taught me. Three generations of knowledge.",
      mediaURLs: [],
    },
    hearts: ['peggy', 'shelby', 'timothy', 'bennett'],
    comments: [
      {
        id: 'comment-6-1',
        authorId: 'bennett',
        authorName: 'Bennett Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=bennett',
        text: 'Thanks Grandpa! I already used it when my friend had a flat tire.',
        createdAt: new Date('2026-01-23T15:00:00'),
      },
      {
        id: 'comment-6-2',
        authorId: 'timothy',
        authorName: 'Timothy Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=timothy',
        text: 'Dad, you taught me the same way. Thanks for keeping the tradition going.',
        createdAt: new Date('2026-01-23T16:00:00'),
      },
    ],
    createdAt: new Date('2026-01-23T14:30:00'),
    updatedAt: new Date('2026-01-23T14:30:00'),
  },
  {
    id: '7',
    type: 'prompt_response',
    authorId: 'ember',
    authorName: 'Ember Herman',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=ember',
    content: {
      text: "My favorite family tradition is Christmas morning breakfast. Grandma's cinnamon rolls, everyone in pajamas, and opening presents together.",
      promptId: 'prompt2',
      promptText: "What's your favorite family tradition?",
    },
    hearts: ['peggy', 'shelby', 'ella', 'eli'],
    comments: [
      {
        id: 'comment-7-1',
        authorId: 'peggy',
        authorName: 'Peggy Deleenheer',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=peggy',
        text: 'I\'m so glad you love my cinnamon rolls! I\'ll teach you the recipe soon.',
        createdAt: new Date('2026-01-22T12:00:00'),
      },
      {
        id: 'comment-7-2',
        authorId: 'ella',
        authorName: 'Ella Fu',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=ella',
        text: 'Same! Christmas morning is the best. Can\'t wait for this year!',
        createdAt: new Date('2026-01-22T13:00:00'),
      },
    ],
    createdAt: new Date('2026-01-22T11:00:00'),
    updatedAt: new Date('2026-01-22T11:00:00'),
  },
  {
    id: '8',
    type: 'milestone',
    authorId: 'eli',
    authorName: 'Eli Herman',
    authorPhotoURL: 'https://i.pravatar.cc/150?u=eli',
    content: {
      text: "Just launched The Vine app! Built it to help our family stay connected. Hope you all enjoy it.",
      mediaURLs: [],
    },
    hearts: ['peggy', 'ron', 'shelby', 'timothy', 'ella', 'preston', 'bennett', 'ember'],
    comments: [
      {
        id: 'comment-8-1',
        authorId: 'shelby',
        authorName: 'Shelby Herman',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=shelby',
        text: 'So proud of you honey! This is wonderful.',
        createdAt: new Date('2026-01-21T17:00:00'),
      },
      {
        id: 'comment-8-2',
        authorId: 'preston',
        authorName: 'Preston Fu',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=preston',
        text: 'Great work Eli! The app looks amazing. Fellow developer here - impressed!',
        createdAt: new Date('2026-01-21T17:30:00'),
      },
      {
        id: 'comment-8-3',
        authorId: 'ron',
        authorName: 'Ron Deleenheer',
        authorPhotoURL: 'https://i.pravatar.cc/150?u=ron',
        text: 'Technology keeps getting better! Your grandma and I are excited to use it.',
        createdAt: new Date('2026-01-21T18:00:00'),
      },
    ],
    createdAt: new Date('2026-01-21T16:00:00'),
    updatedAt: new Date('2026-01-21T16:00:00'),
  },
];

export const mockPrompts = [
  {
    id: 'prompt1',
    text: 'What was the best advice your parents gave you?',
    category: 'life_lessons' as const,
    isActive: true,
  },
  {
    id: 'prompt2',
    text: "What's your favorite family tradition?",
    category: 'family_traditions' as const,
    isActive: true,
  },
  {
    id: 'prompt3',
    text: 'What was your favorite childhood memory?',
    category: 'childhood' as const,
    isActive: true,
  },
];
